version: 2  #version of dbt/api
sources:
  - name: s3
    tables:
      - name: fish
        description: fish_dataset
        meta:
          external_location: "read_parquet('s3://fish-project/fishes/fishes.snappy.parquet')"

      - name: waterquality
        description: waterquality_dataset
        meta:
          external_location: "read_parquet('s3://fish-project/waterqualities/waterqualities.snappy.parquet')"